version: "3.6"

services:
  db:
    container_name: "db"
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: neomovie
      MYSQL_USER: taker
      MYSQL_PASSWORD: taker
    cap_add:
      - SYS_NICE
    networks:
      - api-tier
      - db-admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-admin
  api:
    restart: always
    depends_on:
      - db
    build: ./api
    ports:
      - "5001:80"
    environment:
      FLASK_DEBUG: 1
    networks:
      - api-tier
      - web-tier
  web:
    restart: always
    depends_on:
      - db
    build: ./web
    ports:
      - "5000:80"
    networks:
      - web-tier

volumes:
  db_data: {}

networks:
  web-tier: {}
  api-tier: {}
  db-admin: {}