version: "3"

services:
  db:
    container_name: "db"
    restart: always
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: taker
      MYSQL_DATABASE: taker
      MYSQL_USER: taker
      MYSQL_PASSWORD: taker
  api:
    restart: always
    depends_on:
      - db
    build: ./api
    ports:
      - "5001:80"
  web:
    restart: always
    depends_on:
      - db
    build: ./web
    ports:
      - "5000:80"

volumes:
  db_data: {}